CREATE TABLE IF NOT EXISTS CATALOGUES (
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(12) NOT NULL COMMENT '分类标题',
    thumbnail VARCHAR(64) NOT NULL COMMENT '分类图片',
    sort INT(16) UNSIGNED NOT NULL DEFAULT 0 COMMENT '排序',
    status TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '状态 0 正常 1 禁用',
    created_at TIMESTAMP NOT NULL DEFAULT NOW() COMMENT '创建时间'
)