CREATE TABLE IF NOT EXISTS PRODUCTS (
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(12) NOT NULL COMMENT '产品标题',
    price int(12) UNSIGNED NOT NULL DEFAULT 0 COMMENT '价格',
    sub_title VARCHAR(128) NOT NULL COMMENT '产品简介',
    thumbnail VARCHAR(64) NOT NULL COMMENT '用户名',
	pictures JSON NOT NULL COMMENT "产品大图",
    catalogue_id INT(64) UNSIGNED NOT NULL COMMENT '分类id',
    sort INT(16) UNSIGNED NOT NULL DEFAULT 0 COMMENT '排序',
    description TEXT NOT NULL COMMENT "产品描述",
    status TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '状态 0 正常 1 下架 2 售罄',
    created_at TIMESTAMP NOT NULL DEFAULT NOW() COMMENT '创建时间'
)