CREATE TABLE IF NOT EXISTS PRODUCTS (
    ID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(12) NOT NULL COMMENT '产品标题',
    SUB_TITLE VARCHAR(128) NOT NULL COMMENT '产品简介',
    THUMBNAIL VARCHAR(64) NOT NULL COMMENT '用户名',
	PICTURES JSON NOT NULL COMMENT "产品大图",
    CATALOGUE_ID INT(64) UNSIGNED NOT NULL COMMENT '分类id',
    SORT INT(16) UNSIGNED NOT NULL DEFAULT 0 COMMENT '排序',
    DESCRIPTION TEXT NOT NULL COMMENT "产品描述",
    STATUS TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '状态 0 正常 1 下架 2 售罄',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW() COMMENT '创建时间'
)