CREATE TABLE IF NOT EXISTS USERS (
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nickname VARCHAR(12) COMMENT '昵称',
    username VARCHAR(64) NOT NULL COMMENT '用户名',
    phone VARCHAR(16) NOT NULL COMMENT '电话号码',
    password VARCHAR(128) NOT NULL COMMENT '密码',
    gender TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '性别 0 男 1女',
    avatar VARCHAR(128) COMMENT '头像',
    status TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '状态 0 正常 1 禁用',
    created_at TIMESTAMP NOT NULL DEFAULT NOW() COMMENT '注册时间'
);